name: squidgame
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_core: 1.8.0
  firebase_auth: 3.1.4
  flutter_secure_storage: 4.2.1
  cloud_firestore: 2.5.4
  curved_navigation_bar: 1.0.1
  cached_network_image: 3.1.0
  carousel_slider: 4.0.0
  flutter_barcode_scanner: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: OpenSans
      fonts: 
        - asset: assets/fonts/OpenSans.ttf
  uses-material-design: true

